### ISSUE TITLE
Build examples for CI/CD

### ISSUE THREAD

**Issue by vordimous** [khos2ow/hugo-wrapper#40]
Would be nice to have some build examples for common CI/CD pipelines.

For instance, this command is needed to use the wrapper on netlify
`chmod a+x ./hugow && ./hugow --gc --minify --quiet`

**Comment by khos2ow** [comment]
Thank you @vordimous . Would you mind send a PR to update the doc for this?

**Comment by vordimous** [comment]
Sure thing!

**Comment by khos2ow** [comment]
Closed by #41
